volumes:
  vscode-server:
  vscode-server-insiders:

services:
  dev-container:
    build:
      # All paths are relative to .devcontainer
      context: ../docker/devcontainer
      dockerfile: ./Dockerfile
      target: devcontainer
    volumes:
      # Mount local repo as delegated for performance gains
      - ../:/workspace:delegated
      - ../.git/:/workspace/.git:delegated
      # Persist vscode extension directories
      - vscode-server:/home/node/.vscode-server/extensions
      - vscode-server-insiders:/home/node/.vscode-server-insiders/extensions
      # Permit SSH key access for git
      - type: bind
        source: ${HOME}/.ssh
        target: /home/node/.ssh
        read_only: true
